# Generated by Django 3.2.4 on 2021-07-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField()),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('network_status', models.CharField(blank=True, choices=[('No Status', 'No Status'), ('Normal', 'Normal'), ('Disabled', 'Disabled'), ('Unknown', 'Unknown'), ('Warning', 'Warning'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], max_length=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('In Use', 'In Use'), ('Installed', 'Installed'), ('Retired', 'Retired'), ('Missing', 'Missing'), ('Returned', 'Returned')], max_length=15, null=True)),
                ('group', models.ManyToManyField(to='assets.AssetGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
