# Generated by Django 3.2.4 on 2021-07-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vmware_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sis_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hosted_on_vmware', models.BooleanField(default=1)),
                ('service', models.CharField(blank=True, max_length=30, null=True)),
                ('function', models.CharField(blank=True, max_length=30, null=True)),
                ('environment', models.CharField(blank=True, choices=[('Production', 'Production'), ('Development', 'Development'), ('Test', 'Test'), ('Failover', 'Failover')], max_length=30, null=True)),
                ('state', models.CharField(blank=True, choices=[('Powered On', 'Powered On'), ('Powered Off', 'Powered Off')], max_length=30, null=True)),
                ('criticality_phase', models.CharField(blank=True, choices=[('Non Critical Phase 1', 'Non Critical Phase 1'), ('Non Critical Phase 2', 'Non Critical Phase 2'), ('Non Critical Phase 3', 'Non Critical Phase 3'), ('Critical Phase 1', 'Critical Phase 1'), ('Critical Phase 2', 'Critical Phase 1'), ('Critical Phase 3', 'Critical Phase 1'), ('Test Phase', 'Test Phase')], max_length=30, null=True)),
                ('redundant_server', models.CharField(blank=True, max_length=30, null=True)),
                ('root_disk_space', models.CharField(blank=True, max_length=30, null=True)),
                ('os_type', models.CharField(blank=True, max_length=30, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memory', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('disk_space', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assignment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assignmentgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
