# Generated by Django 3.2.4 on 2021-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20210705_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='disk_space',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='root_disk_space',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
