# Generated by Django 3.2.4 on 2021-07-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_sitescopemonitorcurrentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitescopemonitorcurrentstatus',
            name='assignmentGroup',
        ),
        migrations.RemoveField(
            model_name='sitescopemonitorcurrentstatus',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sitescopemonitorcurrentstatus',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='sitescopemonitorcurrentstatus',
            name='ipAddress',
        ),
        migrations.RemoveField(
            model_name='sitescopemonitorcurrentstatus',
            name='os',
        ),
        migrations.RemoveField(
            model_name='sitescopemonitorcurrentstatus',
            name='os_version',
        ),
        migrations.AddField(
            model_name='sitescopemonitorcurrentstatus',
            name='server',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.servers', to_field='sis_name'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='sis_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
