# Generated by Django 3.2.4 on 2021-07-07 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20210706_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, unique=True)),
                ('ps_location', models.CharField(blank=True, max_length=30, null=True)),
                ('zone_location', models.CharField(blank=True, max_length=30, null=True)),
                ('commisionerate_location', models.CharField(blank=True, choices=[('Hyderabad', 'Hyderabad'), ('Cyberabad', 'Cyberabad'), ('Rachakonda', 'Rachakonda')], max_length=30, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('Junction', 'Junction'), ('Viewing Center', 'Viewing Center'), ('CCC', 'CCC'), ('Data Center', 'Data Center'), ('Other', 'Other')], max_length=30, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='nodelaststatuschange',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='reachability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='sub_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.location'),
        ),
    ]
