# Generated by Django 3.2.4 on 2021-07-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20210707_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servers',
            new_name='Server',
        ),
    ]
