# Generated by Django 3.2.4 on 2021-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageTapePolicySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.CharField(max_length=50)),
                ('percentUsed', models.FloatField()),
                ('mediaId', models.SmallIntegerField(verbose_name='Count of media')),
                ('archive', models.SmallIntegerField()),
                ('unavail', models.SmallIntegerField()),
                ('added_time', models.DateTimeField(blank=True, null=True, verbose_name='time added')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUtilSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_system', models.CharField(max_length=50)),
                ('size_TB', models.FloatField()),
                ('usage_percent', models.FloatField()),
                ('added_time', models.DateTimeField(blank=True, null=True, verbose_name='time added')),
            ],
        ),
    ]
