# Generated by Django 3.2.4 on 2021-07-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0007_rename_servers_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDailyReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('No Status', 'No Status'), ('Normal', 'Normal'), ('Disabled', 'Disabled'), ('Unknown', 'Unknown'), ('Warning', 'Warning'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Normal', max_length=15)),
                ('issue', models.CharField(blank=True, default='Working', max_length=300, null=True)),
                ('supportRequired', models.CharField(blank=True, default='Working', max_length=50, null=True)),
                ('incidentNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.CharField(blank=True, max_length=15, null=True)),
                ('reason', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('aging', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Device daily status',
            },
        ),
        migrations.CreateModel(
            name='SlaAchievedOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dateExcel', models.CharField(blank=True, max_length=20, null=True)),
                ('deviceCount', models.IntegerField(blank=True, null=True)),
                ('totalHours', models.FloatField(blank=True, null=True)),
                ('maintenanceHours', models.FloatField(blank=True, null=True)),
                ('unavailableHours', models.FloatField(blank=True, null=True)),
                ('exclusionHours', models.FloatField(blank=True, null=True)),
                ('valueWithoutExclusion', models.FloatField(blank=True, null=True)),
                ('valueWithExclusion', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Sla Achieved',
                'verbose_name_plural': 'Sla Achieved',
                'ordering': ('date', 'slaPoint'),
            },
        ),
        migrations.CreateModel(
            name='SlaPoint',
            fields=[
                ('slaPoint', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=300)),
                ('Metrics', models.CharField(blank=True, max_length=15, null=True)),
                ('baselineMetric', models.FloatField(blank=True, null=True)),
                ('baselinePoints', models.FloatField(blank=True, null=True)),
                ('lowerPerfomanceMetric', models.FloatField(blank=True, null=True)),
                ('lowerPerfomancePoints', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sla Point',
                'verbose_name_plural': 'Sla Points',
            },
        ),
        migrations.AddConstraint(
            model_name='slapoint',
            constraint=models.UniqueConstraint(fields=('slaPoint',), name='slaPoint'),
        ),
        migrations.AddField(
            model_name='slaachievedoverview',
            name='slaPoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.slapoint'),
        ),
        migrations.AddField(
            model_name='devicedailyreportstatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.networkdevice'),
        ),
        migrations.AddConstraint(
            model_name='slaachievedoverview',
            constraint=models.UniqueConstraint(fields=('date', 'slaPoint'), name='slapoint + date'),
        ),
        migrations.AddConstraint(
            model_name='devicedailyreportstatus',
            constraint=models.UniqueConstraint(fields=('device', 'date'), name='device daily status duplicate entry'),
        ),
    ]
