# Generated by Django 3.2.4 on 2021-07-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slapoint',
            name='slaPoint',
        ),
        migrations.AddField(
            model_name='slapoint',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slapoint',
            name='slaPoint',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
