# Generated by Django 3.2.4 on 2021-07-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210707_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaachievedoverview',
            name='slaPoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.slapoint', to_field='slaPoint'),
        ),
    ]
